// //comparision operator => output boolean

let a=10
console.log(typeof a)

let b="sham"
console.log(typeof b)

let c='30'
console.log(typeof c)

let d= false
console.log(typeof d)

let e=true
console.log(typeof e)


// //< , >, <=, >= , ==, != , ===, !==

console.log(10 < 20)//true
console.log(20 > 10) //true
console.log(7 <= 7) //true
console.log(20 >= 30) //false
console.log(5 == 5) //true
console.log(7 == '7') //true
console.log(5 != '5') //false
console.log(8 !== '8') //true
console.log(10 === 20) //false
console.log(10 === 10)//true

// //logical operator
//AND ==> &&

//true && true  => true
//true && false => false
//false && true => false
//false && false => false

console.log(6 == 6 && 6 !== '6')// true
console.log(7 == 7 && 6 <= 5) // false
console.log(6 > 7 && 6 == 6) // false
console.log(10 == 20 && 5 != 5) // false


// //OR
//true || true  => true
//true ||  false => true
//false || true =>  true
//false || false =>  false

console.log(6 == 6 || 6 !== '6') //true
console.log(7 == 7 || 6 <= 5)  //true
console.log(6 > 7 || 6 == 6) // true
console.log(10 == 20 || 5 != 5)  //false

// //NOT
// //true => false
// //false => true
console.log(!(5 == 5))

console.log(!(7 > 10))


//  git config --global user.email "you@example.com"
//   git config --global user.name "Your Name"

// git branch -M main
// git remote add origin https://github.com/Sayali610/Js.git
// git push -u origin main

// git remote add origin https://github.com/Sayali610/Js.git
// git branch -M main
// git push -u origin main









// //OR ==> ||
// //NOT ==> 